/**
 * Simple TripApp API
 * This is a simple TripApp API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.User;
import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PurchaseCode {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("code")
  private UUID code = null;
  @SerializedName("value")
  private Double value = null;
  @SerializedName("genarationDateTime")
  private Date genarationDateTime = null;
  @SerializedName("usageDateTime")
  private Date usageDateTime = null;
  @SerializedName("used")
  private Boolean used = null;
  @SerializedName("user")
  private User user = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getCode() {
    return code;
  }
  public void setCode(UUID code) {
    this.code = code;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Double getValue() {
    return value;
  }
  public void setValue(Double value) {
    this.value = value;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getGenarationDateTime() {
    return genarationDateTime;
  }
  public void setGenarationDateTime(Date genarationDateTime) {
    this.genarationDateTime = genarationDateTime;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getUsageDateTime() {
    return usageDateTime;
  }
  public void setUsageDateTime(Date usageDateTime) {
    this.usageDateTime = usageDateTime;
  }

  /**
   * Already used by a user.
   **/
  @ApiModelProperty(required = true, value = "Already used by a user.")
  public Boolean getUsed() {
    return used;
  }
  public void setUsed(Boolean used) {
    this.used = used;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public User getUser() {
    return user;
  }
  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseCode purchaseCode = (PurchaseCode) o;
    return (this.id == null ? purchaseCode.id == null : this.id.equals(purchaseCode.id)) &&
        (this.code == null ? purchaseCode.code == null : this.code.equals(purchaseCode.code)) &&
        (this.value == null ? purchaseCode.value == null : this.value.equals(purchaseCode.value)) &&
        (this.genarationDateTime == null ? purchaseCode.genarationDateTime == null : this.genarationDateTime.equals(purchaseCode.genarationDateTime)) &&
        (this.usageDateTime == null ? purchaseCode.usageDateTime == null : this.usageDateTime.equals(purchaseCode.usageDateTime)) &&
        (this.used == null ? purchaseCode.used == null : this.used.equals(purchaseCode.used)) &&
        (this.user == null ? purchaseCode.user == null : this.user.equals(purchaseCode.user));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.genarationDateTime == null ? 0: this.genarationDateTime.hashCode());
    result = 31 * result + (this.usageDateTime == null ? 0: this.usageDateTime.hashCode());
    result = 31 * result + (this.used == null ? 0: this.used.hashCode());
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseCode {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  code: ").append(code).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  genarationDateTime: ").append(genarationDateTime).append("\n");
    sb.append("  usageDateTime: ").append(usageDateTime).append("\n");
    sb.append("  used: ").append(used).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
